### PR TITLE
Changed nvidia mode so that it would not depend on the integrated graphics card

### PR DESCRIPTION
**Pull request by Boria138**
I took the information from here (https://github.com/pop-os/system76-power/blob/master/src/graphics.rs#L84 )

### CODE REVIEW

**Comment by Boria138** [comment]
Since I do not have an integrated card from AMD, the code has not been tested, so I would like someone to test the operabilit

**Comment by bayasdev** [comment]
@Boria138 I applied the same trick on early versions of Envycontrol but it didn't work on AMD systems

**Comment by Boria138** [comment]
> @Boria138 I applied the same trick on early versions of Envycontrol but it didn't work on AMD systems

Hmm weird, as far as I understand PopOS and Fedora that's how they switch the card, maybe they just turned a blind eye to the fact that it doesn't work on amd, or maybe there's some extra stuff I didn't notice.

**Comment by Boria138** [comment]
@bayasdev Could you post the commit where you used this, maybe our code is a bit different, because I don't think Fedora would recommend a semi-working solution like PopOS does

**Comment by bayasdev** [comment]
> @bayasdev Could you post the commit where you used this, maybe our code is a bit different, because I don't think Fedora would recommend a semi-working solution like PopOS does

If you're referring to [this article](https://docs.fedoraproject.org/en-US/quick-docs/set-nvidia-as-primary-gpu-on-optimus-based-laptops/) then yeah it doesn't work on AMD

**Comment by Boria138** [comment]
I found this post, although I don't know if it will work.

https://forums.linuxmint.com/viewtopic.php?t=333833

**Comment by Boria138** [comment]
> > @bayasdev Could you post the commit where you used this, maybe our code is a bit different, because I don't think Fedora would recommend a semi-working solution like PopOS does
> 
> If you're referring to [this article](https://docs.fedoraproject.org/en-US/quick-docs/set-nvidia-as-primary-gpu-on-optimus-based-laptops/) then yeah it doesn't work on AMD

I based on PopOS

**Comment by Boria138** [comment]
> > @bayasdev Could you post the commit where you used this, maybe our code is a bit different, because I don't think Fedora would recommend a semi-working solution like PopOS does
> 
> If you're referring to [this article](https://docs.fedoraproject.org/en-US/quick-docs/set-nvidia-as-primary-gpu-on-optimus-based-laptops/) then yeah it doesn't work on AMD

I based on PopOS

**Comment by Boria138** [comment]
> > @bayasdev Could you post the commit where you used this, maybe our code is a bit different, because I don't think Fedora would recommend a semi-working solution like PopOS does
> 
> If you're referring to [this article](https://docs.fedoraproject.org/en-US/quick-docs/set-nvidia-as-primary-gpu-on-optimus-based-laptops/) then yeah it doesn't work on AMD

I based on PopOS

**Comment by Boria138** [comment]
@bayasdev I've rewritten the code a bit, it should work with amdgpu now, but I need tests

**Comment by pingarelho** [comment]
What is this PR trying to achieve, exactly? I have a Ryzen 4600H + GTX 1650 laptop I can test with.

**Comment by Boria138** [comment]
> What is this PR trying to achieve, exactly? I have a Ryzen 4600H + GTX 1650 laptop I can test with.

Now integrated mode works exclusively in Nvidia + Intel bundle, in case of AMD Nvidia continues to consume power even in integrated mode, this pr should fix that

**Comment by bayasdev** [comment]
> > What is this PR trying to achieve, exactly? I have a Ryzen 4600H + GTX 1650 laptop I can test with.
> 
> Now integrated mode works exclusively in Nvidia + Intel bundle, in case of AMD Nvidia continues to consume power even in integrated mode, this pr should fix that

That's not how it works, also your PR does nothing for integrated mode

**Comment by Boria138** [comment]
> > > What is this PR trying to achieve, exactly? I have a Ryzen 4600H + GTX 1650 laptop I can test with.
> > 
> > Now integrated mode works exclusively in Nvidia + Intel bundle, in case of AMD Nvidia continues to consume power even in integrated mode, this pr should fix that
> 
> That's not how it works, also your PR does nothing for integrated mode

Oh yeah right everything is exactly the opposite of what these fixes affect Nvidia mode, since they were delayed for a couple of days I forgot what exactly was added

**Pull request closed without merging**
