### PR TITLE
Added documentation for man pages

### PR DESCRIPTION
**Pull request by ricardovg4**

### CODE REVIEW

**Comment by geminis3** [comment]
Hello Ricardo, thanks for your contribution however I'm not sure how this should be implemented (copying it to `/usr/local/man/man8` ?).

Currently EnvyControl is only packaged for Arch Linux distros (AUR).

**Comment by ricardovg4** [comment]
Hello Geminis3, copying it to /usr/share/man/man8/ would do the trick. This could be on the PKGBUILD itself.

**Comment by DaVikingMan** [comment]
Instead of including it on the PKGBUILD, we might be able to include it in the 'setup.py' so that people who are building the package from source can also access the man pages

**Comment by sunwire** [comment]
> Hello Ricardo, thanks for your contribution however I'm not sure how this should be implemented

Just add to setup.py
`data_files = [('man/man8', ['doc/envycontrol.8'])],`

**Comment by bayasdev** [comment]
@DaVikingMan @ricardovg4 @sunwire if anyone wants to add man pages support please open a new PR

**Pull request closed without merging**
